### ISSUE TITLE
Cannot run samples

### ISSUE THREAD

**Issue by boldtrn** [osmlab/osmdiff#10]
I just tried to run the first sample provided. I installed this lib using pip on Ubuntu 18.04 LTS and python 2.7.

I created a file `test.py` with the following content:
```
from osmdiff import OSMChange
o = OSMChange(debug='TRUE')
o.frequency = "minute"  # the default
o.get_state()  # retrieve current sequence ID
print(o.sequence_number)
o.retrieve()  # retrieve from API
o
```

I get the following output:
```
#Mon Jan 21 10:37:04 UTC 2019
sequenceNumber=3332150
txnMaxQueried=1950982863
txnActiveList=1950982219
txnReadyList=
txnMax=1950982863
timestamp=2019-01-21T10\:37\:02Z

3332150
https://planet.openstreetmap.org/replication/minute/003/332/150.osc.gz
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    o.retrieve()  # retrieve from API
  File "/usr/local/lib/python2.7/dist-packages/osmdiff/diff.py", line 201, in retrieve
    self._parse_stream(gzfile)
  File "/usr/local/lib/python2.7/dist-packages/osmdiff/diff.py", line 177, in _parse_stream
    for event, elem in cElementTree.iterparse(stream):
  File "<string>", line 100, in next
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 296, in _read
    self.fileobj.seek(0, 2)     # Seek to end of file
io.UnsupportedOperation: seek
```

To me it looks like there might be an issue with downloading/reading the osc.gz.

When I manually download the osc.gz file and extract it and provide it in the script like this:
```
o = OSMChange(file='150.osc', debug='TRUE')
```

The script fails like this:
```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    o = OSMChange(file='150.xml', debug='TRUE')
  File "/usr/local/lib/python2.7/dist-packages/osmdiff/diff.py", line 146, in __init__
    self._parse_stream(fh)
  File "/usr/local/lib/python2.7/dist-packages/osmdiff/diff.py", line 181, in _parse_stream
    self._build_action(elem)
  File "/usr/local/lib/python2.7/dist-packages/osmdiff/diff.py", line 188, in _build_action
    o = OSMObject.from_xml(thing)
  File "/usr/local/lib/python2.7/dist-packages/osmdiff/osm/osm.py", line 41, in from_xml
    o = Node()
  File "/usr/local/lib/python2.7/dist-packages/osmdiff/osm/osm.py", line 59, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
``` 

Am I doing something wrong?

**Comment by mvexel** [comment]
The library is not written for Python 2.x, sorry. I'll clarify in the README if it is not already there.
